algoritmo "multa de um carro"
var
velocidade:real
valormulta:inteiro
    cobranca:real
 inicio
 
 escreva("qual  a sua velocidade em (km) ?:")
 leia(velocidade)
 
   
  se   velocidade >=80 entao
  escreval("=====Multado em R$:=====,")

  valormulta<-5
   cobranca<- valormulta + velocidade
    escreval(cobranca)
    fimse
    
    escreval("a sua velocidade foi de :", velocidade)
    fimalgoritmo